apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.org }}:{{ .Chart.Name }}:{{ .Values.hypershiftDeploymentOperator.leaderRoleName }}
  namespace: {{ .Values.global.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.org }}:{{ .Chart.Name }}:{{ .Values.hypershiftDeploymentOperator.leaderRoleName }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.hypershiftDeploymentOperator.serviceaccount }}
  namespace: {{ .Values.global.namespace }}
