apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.org }}:{{ .Chart.Name }}:{{ .Values.hypershiftDeploymentOperator.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.org }}:{{ .Chart.Name }}:{{ .Values.hypershiftDeploymentOperator.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.hypershiftDeploymentOperator.serviceaccount }}
  namespace: {{ .Values.global.namespace }}

